### ISSUE TITLE
Stabilize system

### ISSUE THREAD

**Issue by zaesur** [zaesur/fight-night#12]
Make sure there can be no 'indeterminate' states, where hardware and UI are misaligned.

**Comment by citizenveen** [comment]
'open vote' should also reset the screen to white (so you can start a vote straight from black).
'Black background' or 'white background' should also close the vote if one is open.

**Comment by zaesur** [comment]
@citizenveen I'll create issues for these specific bugs

**Comment by zaesur** [comment]
@citizenveen in what scenario would you want to go from an open vote to a blank screen though?

**Comment by citizenveen** [comment]
Generally you don't, but to have a more bug free system.
Say a technician opens a vote by accident, they might want to press 'white screen' quickly because they will want to 'erase' the screen, then seeing a white screen, with an open voting might be confusing.
Not the most important issue
