### ISSUE TITLE
Implement seperate publish buttons per answer

### ISSUE THREAD

**Issue by citizenveen** [zaesur/fight-night#14]

**Comment by citizenveen** [comment]
makeup of publishing does not seem correct, the makeup file from Nick might suggest a wrong makeup.
Send email to designer to request clarity. Will probably need to implement a change.

**Comment by zaesur** [comment]
@citizenveen I've implemented it per Nick's design, but with consideration we might need to show multiple items rather than single options. This is an easy fix after we get feedback from Nick.
